# data.py

# Список городов для фильтра
CITIES = ['Алматы', 'Астана', 'Шымкент']

# Полная база данных университетов
universities = [
    # --- АЛМАТЫ ---
    {
        'id': 'kaznu',
        'name': 'КазНУ',
        'fullName': 'Казахский Национальный Университет им. аль-Фараби',
        'city': 'Алматы',
        'type': 'Государственный',
        'direction': 'Многопрофильный',
        'tuition': 1100000,
        'rating': 4.9,
        'desc': 'Главный национальный вуз страны. Лидер в рейтингах QS. Огромный кампус "Казгуград".',
        'color': 'from-blue-600 to-cyan-500',
        'imageUrl': "https://placehold.co/1200x400/2563eb/ffffff?text=KazNU+Campus",
        'stats': {'employment': 92, 'grant': 85, 'students': 25000},
        'features': ['Огромный кампус', 'Международные связи', 'Военная кафедра'],
        'contacts': {'phone': '+7 (727) 377-33-33', 'email': 'info@kaznu.kz', 'address': 'г. Алматы, пр. аль-Фараби 71'},
        'mapEmbedUrl': ''
    },
    {
        'id': 'kbtu',
        'name': 'КБТУ',
        'fullName': 'Казахстанско-Британский Технический Университет',
        'city': 'Алматы',
        'type': 'Частный',
        'direction': 'IT и Нефтегаз',
        'tuition': 1800000,
        'rating': 4.8,
        'desc': 'Топовый технический вуз. Лучшие программисты и нефтяники выходят отсюда.',
        'color': 'from-blue-800 to-indigo-900',
        'imageUrl': "https://placehold.co/1200x400/1e3a8a/ffffff?text=KBTU+Building",
        'stats': {'employment': 98, 'grant': 40, 'students': 4000},
        'features': ['Обучение на английском', 'Связи с Shell/Chevron', 'Центр Алматы'],
        'contacts': {'phone': '+7 (727) 357-42-42', 'email': 'info@kbtu.kz', 'address': 'г. Алматы, ул. Толе би 59'},
        'mapEmbedUrl': ''
    },
    {
        'id': 'satbayev',
        'name': 'Satbayev',
        'fullName': 'Satbayev University (Политех)',
        'city': 'Алматы',
        'type': 'Государственный',
        'direction': 'Инженерия',
        'tuition': 950000,
        'rating': 4.7,
        'desc': 'Старейший технический вуз. Инженеры, архитекторы, геологи.',
        'color': 'from-green-600 to-teal-600',
        'imageUrl': "https://placehold.co/1200x400/059669/ffffff?text=Satbayev+University",
        'stats': {'employment': 90, 'grant': 70, 'students': 15000},
        'features': ['Сильная инженерия', 'Общежития', 'Научные лаборатории'],
        'contacts': {'phone': '+7 (727) 292-60-25', 'email': 'info@satbayev.university', 'address': 'г. Алматы, ул. Сатпаева 22'},
        'mapEmbedUrl': ''
    },
    {
        'id': 'kimep',
        'name': 'KIMEP',
        'fullName': 'Университет КИМЭП',
        'city': 'Алматы',
        'type': 'Частный',
        'direction': 'Бизнес и Право',
        'tuition': 2500000,
        'rating': 4.8,
        'desc': 'Лидер в бизнес-образовании западного образца. Обучение полностью на английском.',
        'color': 'from-purple-700 to-pink-600',
        'imageUrl': "https://placehold.co/1200x400/7e22ce/ffffff?text=KIMEP",
        'stats': {'employment': 96, 'grant': 20, 'students': 3000},
        'features': ['Западный диплом', 'Студенческая жизнь', 'Бизнес-связи'],
        'contacts': {'phone': '+7 (727) 270-43-15', 'email': 'admission@kimep.kz', 'address': 'г. Алматы, пр. Абая 2'},
        'mapEmbedUrl': ''
    },
    {
        'id': 'asfend',
        'name': 'КазНМУ',
        'fullName': 'КазНМУ им. Асфендиярова',
        'city': 'Алматы',
        'type': 'Государственный',
        'direction': 'Медицина',
        'tuition': 1200000,
        'rating': 4.6,
        'desc': 'Главная кузница врачей Казахстана. Хирургия, стоматология, педиатрия.',
        'color': 'from-red-600 to-rose-500',
        'imageUrl': "https://placehold.co/1200x400/e11d48/ffffff?text=Medical+University",
        'stats': {'employment': 99, 'grant': 60, 'students': 10000},
        'features': ['Собственные клиники', 'Симуляционный центр', 'Международные стажировки'],
        'contacts': {'phone': '+7 (727) 338-70-90', 'email': 'info@kaznmu.kz', 'address': 'г. Алматы, ул. Толе би 94'},
        'mapEmbedUrl': ''
    },

    # --- АСТАНА ---
    {
        'id': 'nu',
        'name': 'NU',
        'fullName': 'Nazarbayev University',
        'city': 'Астана',
        'type': 'Назарбаев Университет',
        'direction': 'Наука и Технологии',
        'tuition': 0, 
        'rating': 5.0,
        'desc': 'Исследовательский университет мирового уровня. Обучение бесплатное (по гранту).',
        'color': 'from-yellow-500 to-orange-500',
        'imageUrl': "https://placehold.co/1200x400/f59e0b/ffffff?text=Nazarbayev+University",
        'stats': {'employment': 94, 'grant': 95, 'students': 6000},
        'features': ['Мировой уровень', 'Бесплатное обучение', 'Научные центры'],
        'contacts': {'phone': '+7 (7172) 70-66-88', 'email': 'info@nu.edu.kz', 'address': 'г. Астана, пр. Кабанбай батыра 53'},
        'mapEmbedUrl': ''
    },
    {
        'id': 'enu',
        'name': 'ENU',
        'fullName': 'Евразийский Национальный Университет',
        'city': 'Астана',
        'type': 'Государственный',
        'direction': 'Многопрофильный',
        'tuition': 900000,
        'rating': 4.7,
        'desc': 'Один из ведущих вузов столицы. Сильные гуманитарные и естественно-научные специальности.',
        'color': 'from-blue-500 to-indigo-500',
        'imageUrl': "https://placehold.co/1200x400/3b82f6/ffffff?text=ENU+Astana",
        'stats': {'employment': 88, 'grant': 75, 'students': 20000},
        'features': ['В центре столицы', 'Общежития', 'Академическая мобильность'],
        'contacts': {'phone': '+7 (7172) 70-95-00', 'email': 'enu@enu.kz', 'address': 'г. Астана, ул. Сатпаева 2'},
        'mapEmbedUrl': ''
    },
    {
        'id': 'aitu',
        'name': 'Astana IT',
        'fullName': 'Astana IT University',
        'city': 'Астана',
        'type': 'Государственный',
        'direction': 'IT и Инновации',
        'tuition': 1000000,
        'rating': 4.8,
        'desc': 'Новый вуз, сфокусированный исключительно на IT. Обучение за 3 года (триместры).',
        'color': 'from-emerald-500 to-teal-500',
        'imageUrl': "https://placehold.co/1200x400/10b981/ffffff?text=Astana+IT",
        'stats': {'employment': 97, 'grant': 90, 'students': 3000},
        'features': ['Обучение 3 года', 'Современное здание', 'EXPO-центр'],
        'contacts': {'phone': '+7 (7172) 64-57-10', 'email': 'info@astanait.edu.kz', 'address': 'г. Астана, пр. Мангилик Ел C1'},
        'mapEmbedUrl': ''
    },
    {
        'id': 'kazguu',
        'name': 'KAZGUU',
        'fullName': 'Университет КАЗГЮУ им. Нарикбаева',
        'city': 'Астана',
        'type': 'Частный',
        'direction': 'Право и Экономика',
        'tuition': 1300000,
        'rating': 4.6,
        'desc': 'Лучший юридический вуз страны. Сильная бизнес-школа и переводческое дело.',
        'color': 'from-slate-700 to-slate-900',
        'imageUrl': "https://placehold.co/1200x400/334155/ffffff?text=KAZGUU",
        'stats': {'employment': 93, 'grant': 30, 'students': 5000},
        'features': ['Лучшие юристы', 'Английский язык', 'Современная библиотека'],
        'contacts': {'phone': '+7 (7172) 70-30-30', 'email': 'info@kazguu.kz', 'address': 'г. Астана, ш. Коргалжын 8'},
        'mapEmbedUrl': ''
    },
    {
        'id': 'kazatu',
        'name': 'КазАТУ',
        'fullName': 'КазАТУ им. С.Сейфуллина',
        'city': 'Астана',
        'type': 'Государственный',
        'direction': 'Агротехнологии',
        'tuition': 700000,
        'rating': 4.4,
        'desc': 'Крупнейший аграрный и технический вуз. Ветеринария, архитектура, энергетика.',
        'color': 'from-green-700 to-lime-600',
        'imageUrl': "https://placehold.co/1200x400/15803d/ffffff?text=KazATU",
        'stats': {'employment': 85, 'grant': 80, 'students': 12000},
        'features': ['Военная кафедра', 'Собственные поля', 'Бюджетное обучение'],
        'contacts': {'phone': '+7 (7172) 31-75-47', 'email': 'canc@kazatu.kz', 'address': 'г. Астана, пр. Победы 62'},
        'mapEmbedUrl': ''
    },

    # --- ШЫМКЕНТ ---
    {
        'id': 'sku',
        'name': 'ЮКУ',
        'fullName': 'ЮКУ им. М.Ауэзова',
        'city': 'Шымкент',
        'type': 'Государственный',
        'direction': 'Многопрофильный',
        'tuition': 600000,
        'rating': 4.5,
        'desc': 'Самый крупный вуз на юге Казахстана. Огромный выбор специальностей.',
        'color': 'from-indigo-600 to-violet-600',
        'imageUrl': "https://placehold.co/1200x400/4f46e5/ffffff?text=Auezov+University",
        'stats': {'employment': 82, 'grant': 70, 'students': 30000},
        'features': ['Большой выбор', 'Доступное обучение', 'Активная молодежь'],
        'contacts': {'phone': '+7 (7252) 21-01-41', 'email': 'info@auezov.edu.kz', 'address': 'г. Шымкент, пр. Тауке хана 5'},
        'mapEmbedUrl': ''
    },
    {
        'id': 'skma',
        'name': 'ЮКМА',
        'fullName': 'Южно-Казахстанская Медицинская Академия',
        'city': 'Шымкент',
        'type': 'Государственный',
        'direction': 'Медицина',
        'tuition': 950000,
        'rating': 4.6,
        'desc': 'Подготовка врачей и фармацевтов для всего южного региона. Сильная фармацевтика.',
        'color': 'from-teal-500 to-green-500',
        'imageUrl': "https://placehold.co/1200x400/14b8a6/ffffff?text=SKMA+Medicine",
        'stats': {'employment': 95, 'grant': 50, 'students': 5000},
        'features': ['Фармацевтика', 'Клиническая база', 'Сильные преподаватели'],
        'contacts': {'phone': '+7 (7252) 40-82-22', 'email': 'info@ukma.kz', 'address': 'г. Шымкент, пл. Аль-Фараби 1'},
        'mapEmbedUrl': ''
    },
    {
        'id': 'tashenov',
        'name': 'Tashenov',
        'fullName': 'Университет им. Ж.Ташенева',
        'city': 'Шымкент',
        'type': 'Частный',
        'direction': 'Педагогика и Бизнес',
        'tuition': 450000,
        'rating': 4.0,
        'desc': 'Доступное образование, упор на педагогические кадры и экономику.',
        'color': 'from-orange-500 to-red-500',
        'imageUrl': "https://placehold.co/1200x400/f97316/ffffff?text=Tashenov+University",
        'stats': {'employment': 75, 'grant': 20, 'students': 6000},
        'features': ['Низкая цена', 'Гибкий график', 'Новые корпуса'],
        'contacts': {'phone': '+7 (7252) 53-09-90', 'email': 'info@tashenov.kz', 'address': 'г. Шымкент, ул. Конаева 15'},
        'mapEmbedUrl': ''
    },
    {
        'id': 'miras',
        'name': 'Miras',
        'fullName': 'Университет Мирас',
        'city': 'Шымкент',
        'type': 'Частный',
        'direction': 'Гуманитарный',
        'tuition': 400000,
        'rating': 3.9,
        'desc': 'Один из первых частных вузов Шымкента. Языки, дизайн, психология.',
        'color': 'from-pink-500 to-rose-500',
        'imageUrl': "https://placehold.co/1200x400/ec4899/ffffff?text=Miras+University",
        'stats': {'employment': 70, 'grant': 10, 'students': 4000},
        'features': ['Творческая атмосфера', 'Дизайн', 'Иностранные языки'],
        'contacts': {'phone': '+7 (7252) 43-23-23', 'email': 'info@miras.edu.kz', 'address': 'г. Шымкент, ул. Иляева 3'},
        'mapEmbedUrl': ''
    },
    {
        'id': 'udn',
        'name': 'ХДУ',
        'fullName': 'Народный Университет (Дружбы Народов)',
        'city': 'Шымкент',
        'type': 'Частный',
        'direction': 'Инженерия и Право',
        'tuition': 500000,
        'rating': 4.1,
        'desc': 'Региональный вуз, ориентированный на практические навыки и трудоустройство.',
        'color': 'from-blue-400 to-indigo-400',
        'imageUrl': "https://placehold.co/1200x400/60a5fa/ffffff?text=UDN+Shymkent",
        'stats': {'employment': 78, 'grant': 15, 'students': 4500},
        'features': ['Практика', 'Спорткомплекс', 'Дружный коллектив'],
        'contacts': {'phone': '+7 (7252) 56-78-90', 'email': 'info@udn.kz', 'address': 'г. Шымкент, ул. Рыскулова 10'},
        'mapEmbedUrl': ''
    }
]
